### PR TITLE
fix for items recalculating on resize

### PR DESCRIPTION
**Pull request by eybarta**
Added an update method which simply updates
items height and iOT after window resize

### CODE REVIEW

**Comment by jsnanigans** [comment]
thanks a lot for the PR, but could you please run `npm run build` then I can merge it :)

**Comment by eybarta** [comment]
sure no problem, to clarify.. you want me to add the built lib directory to this PR?

**Comment by jsnanigans** [comment]
Yes that's correct

**Comment by eybarta** [comment]
I've added the 3 built files to the PR

**Comment by jsnanigans** [comment]
Thanks!

**Pull request merged**
